# Generated by Django 5.2.14 on 2026-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelborders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelborderdesign',
            name='border_repeat',
            field=models.CharField(choices=[('stretch', 'Stretch'), ('repeat', 'Repeat'), ('round', 'Round')], default='stretch', max_length=10),
        ),
    ]
